## Youtube

### Préparation de la donnée

In [15]:
import pandas as pd
df = pd.read_csv('videos_shortcat.csv')
df.head()

,title,channel,video_url,views,likes,comments,publishedAt,duration,duration_seconds
0,Nobody has EVER done this in Mario Kart 8 Delu...,Shortcat,https://www.youtube.com/watch?v=eSvU1iXtAIc,170371,10736,854,2025-05-01T16:00:55Z,PT37M54S,2274
1,How good is MAX WATER SPEED in Mario Kart 8 De...,Shortcat,https://www.youtube.com/watch?v=iUOeBUwfugI,229278,10063,748,2025-04-27T16:01:04Z,PT38M,2280
2,Nintendo's TERRIFIC Game Design! | Mario Kart ...,Shortcat,https://www.youtube.com/watch?v=f325OnfSSq4,1139421,70247,605,2025-04-26T16:01:03Z,PT1M31S,91
3,The DREAM TEAM in Competitive Mario Kart 8 Del...,Shortcat,https://www.youtube.com/watch?v=gJmfOsGz4uk,228008,11625,689,2025-04-24T21:04:26Z,PT30M8S,1808
4,"""How are you so good at Mario Kart?"" | Mario K...",Shortcat,https://www.youtube.com/watch?v=YeiQNImGaEo,984027,49905,571,2025-04-23T16:00:52Z,PT1M8S,68

In [16]:
# Séparer les vidéos en deux types : "Short" et "Vidéo"
def detect_type_video(duration):
    if duration <= 180:
        return "Short"
    else:
        return "Vidéo longue"

df["type_video"] = df["duration_seconds"].apply(detect_type_video)
display(df)

,title,channel,video_url,views,likes,comments,publishedAt,duration,duration_seconds,type_video
0,Nobody has EVER done this in Mario Kart 8 Delu...,Shortcat,https://www.youtube.com/watch?v=eSvU1iXtAIc,170371,10736,854,2025-05-01T16:00:55Z,PT37M54S,2274,Vidéo longue
1,How good is MAX WATER SPEED in Mario Kart 8 De...,Shortcat,https://www.youtube.com/watch?v=iUOeBUwfugI,229278,10063,748,2025-04-27T16:01:04Z,PT38M,2280,Vidéo longue
2,Nintendo's TERRIFIC Game Design! | Mario Kart ...,Shortcat,https://www.youtube.com/watch?v=f325OnfSSq4,1139421,70247,605,2025-04-26T16:01:03Z,PT1M31S,91,Short
3,The DREAM TEAM in Competitive Mario Kart 8 Del...,Shortcat,https://www.youtube.com/watch?v=gJmfOsGz4uk,228008,11625,689,2025-04-24T21:04:26Z,PT30M8S,1808,Vidéo longue
4,"""How are you so good at Mario Kart?"" | Mario K...",Shortcat,https://www.youtube.com/watch?v=YeiQNImGaEo,984027,49905,571,2025-04-23T16:00:52Z,PT1M8S,68,Short
...,...,...,...,...,...,...,...,...,...,...
440,EVERY Shortcut on YOSHI CIRCUIT 150cc | Mario ...,Shortcat,https://www.youtube.com/watch?v=JlAeYQQJfQ0,1371587,87767,301,2023-04-11T13:00:21Z,PT58S,58,Short
441,EVERY Shortcut on DK SUMMIT 150cc | Mario Kart...,Shortcat,https://www.youtube.com/watch?v=GJCLFOFlSv0,1521821,104151,311,2023-04-10T18:41:16Z,PT59S,59,Short
442,EVERY Shortcut on BIG BLUE 150cc | Mario Kart ...,Shortcat,https://www.youtube.com/watch?v=IRH789NbyGk,1758964,117956,434,2023-04-08T13:00:11Z,PT52S,52,Short
443,"Mario Kart 8 Deluxe, except I wait 10 seconds ...",Shortcat,https://www.youtube.com/watch?v=wubcV46XBcM,312411,7253,583,2023-04-07T00:34:10Z,PT18M17S,1097,Vidéo longue
444,EVERY Shortcut on WALUIGI STADIUM 150cc | Mari...,Shortcat,https://www.youtube.com/watch?v=MjoswRuHxmw,696909,42943,346,2023-03-31T18:32:30Z,PT58S,58,Short

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 445 entries, 0 to 444
Data columns (total 10 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             445 non-null    object
 1   channel           445 non-null    object
 2   video_url         445 non-null    object
 3   views             445 non-null    int64
 4   likes             445 non-null    int64
 5   comments          445 non-null    int64
 6   publishedAt       445 non-null    object
 7   duration          445 non-null    object
 8   duration_seconds  445 non-null    int64
 9   type_video        445 non-null    object
dtypes: int64(4), object(6)
memory usage: 34.9+ KB

In [18]:
shorts_count = df[df["type_video"] == "Short"].shape[0]
print(f"Nombre de shorts : {shorts_count}")

Nombre de shorts : 302

In [19]:
df_vidéo = df[df["type_video"] == "Vidéo longue"]
df_shorts = df[df["type_video"] == "Short"]

In [20]:
df["publishedAt"] = pd.to_datetime(df["publishedAt"])
df["day_of_week"] = df["publishedAt"].dt.day_name()  # afficher les jours de la semaine de la sortie de la vidéo

In [21]:
df.head()

,title,channel,video_url,views,likes,comments,publishedAt,duration,duration_seconds,type_video,day_of_week
0,Nobody has EVER done this in Mario Kart 8 Delu...,Shortcat,https://www.youtube.com/watch?v=eSvU1iXtAIc,170371,10736,854,2025-05-01 16:00:55+00:00,PT37M54S,2274,Vidéo longue,Thursday
1,How good is MAX WATER SPEED in Mario Kart 8 De...,Shortcat,https://www.youtube.com/watch?v=iUOeBUwfugI,229278,10063,748,2025-04-27 16:01:04+00:00,PT38M,2280,Vidéo longue,Sunday
2,Nintendo's TERRIFIC Game Design! | Mario Kart ...,Shortcat,https://www.youtube.com/watch?v=f325OnfSSq4,1139421,70247,605,2025-04-26 16:01:03+00:00,PT1M31S,91,Short,Saturday
3,The DREAM TEAM in Competitive Mario Kart 8 Del...,Shortcat,https://www.youtube.com/watch?v=gJmfOsGz4uk,228008,11625,689,2025-04-24 21:04:26+00:00,PT30M8S,1808,Vidéo longue,Thursday
4,"""How are you so good at Mario Kart?"" | Mario K...",Shortcat,https://www.youtube.com/watch?v=YeiQNImGaEo,984027,49905,571,2025-04-23 16:00:52+00:00,PT1M8S,68,Short,Wednesday

In [22]:
# ajout d'une colonne ratio entre le nombre de likes et le nombre de vues
df["ratio_likes_views"] = df["likes"] / df["views"] * 100

In [23]:
df.head()

,title,channel,video_url,views,likes,comments,publishedAt,duration,duration_seconds,type_video,day_of_week,ratio_likes_views
0,Nobody has EVER done this in Mario Kart 8 Delu...,Shortcat,https://www.youtube.com/watch?v=eSvU1iXtAIc,170371,10736,854,2025-05-01 16:00:55+00:00,PT37M54S,2274,Vidéo longue,Thursday,6.301542
1,How good is MAX WATER SPEED in Mario Kart 8 De...,Shortcat,https://www.youtube.com/watch?v=iUOeBUwfugI,229278,10063,748,2025-04-27 16:01:04+00:00,PT38M,2280,Vidéo longue,Sunday,4.388995
2,Nintendo's TERRIFIC Game Design! | Mario Kart ...,Shortcat,https://www.youtube.com/watch?v=f325OnfSSq4,1139421,70247,605,2025-04-26 16:01:03+00:00,PT1M31S,91,Short,Saturday,6.165149
3,The DREAM TEAM in Competitive Mario Kart 8 Del...,Shortcat,https://www.youtube.com/watch?v=gJmfOsGz4uk,228008,11625,689,2025-04-24 21:04:26+00:00,PT30M8S,1808,Vidéo longue,Thursday,5.098505
4,"""How are you so good at Mario Kart?"" | Mario K...",Shortcat,https://www.youtube.com/watch?v=YeiQNImGaEo,984027,49905,571,2025-04-23 16:00:52+00:00,PT1M8S,68,Short,Wednesday,5.071507

### Modèle de machine learning

#### Premier modèle
pour objectif de prédire les vues de prochaines vidéo

nous allons utiliser XGBoost

In [24]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from xgboost import XGBRegressor
import numpy as np
import matplotlib.pyplot as plt

In [25]:
start_date = pd.to_datetime("2025-03-01")
end_date = pd.to_datetime("today")

In [27]:
# supprimer le fuseau horaire de la date de publication
df["publishedAt"] = pd.to_datetime(df["publishedAt"]).dt.tz_localize(None)

In [31]:
# Filtrer les vidéos publiées entre le 1er mars 2025 et aujourd'hui
df_filtered = df[(df["publishedAt"] >= start_date) & (df["publishedAt"] <= end_date)]
df_filtered = df_filtered[df_filtered['views'] <= 1000000]  # Garder les vidéos avec moins de 1 million de vues pour éviter de perturber le modèle

In [34]:
df_filtered.columns

Index(['title', 'channel', 'video_url', 'views', 'likes', 'comments',
       'publishedAt', 'duration', 'duration_seconds', 'type_video',
       'day_of_week', 'ratio_likes_views'],
      dtype='object')

In [43]:
target = "views"
features = ["likes", "comments", "duration_seconds", "ratio_likes_views", "type_video", "day_of_week"]

X = df_filtered[features]
y = df_filtered[target]

numeric_features = ["likes", "comments", "duration_seconds", "ratio_likes_views"]
categorical_features = ["type_video", "day_of_week"]

preprocessor = ColumnTransformer(transformers=[
    ("num", "passthrough", numeric_features),
    ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
])

model = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("regressor", XGBRegressor(n_estimators=100, learning_rate=0.1, random_state=42))
])

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

y_train_log = np.log1p(y_train)

model.fit(X_train, y_train_log)

y_pred_log = model.predict(X_test)
y_pred = np.expm1(y_pred_log)

mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

print(f"MAE : {mae:.0f}")
print(f"RMSE : {rmse:.0f}")
print(f"R² : {r2:.2f}")

MAE : 72281
RMSE : 105134
R² : 0.87